GENERAL:
  MODE: "Test"
  OUT_PATH: "output"
  DEVICE: "cuda:0" #cpu
  COMMENT: "vgg11_run1_test"


MODEL: 
  TYPE: "vgg11"
  PRETRAINED: 1

DATA_PARAM:
  TEST: "Datasets/i_Test"
  TRAIN: "Datasets/i_TrainVal"
  AUGMENTATION: 1
  NUM_WORKERS: 4
  BATCH_SIZE: 16

TRAIN_PARAM:
  EPOCH: 200
  TEST_INTERVAL: 10
  LR: 0.00001
  LR_DECAY: 0.75
  WT_DECAY: 0.0
  STEP_SIZE: 15
  PRETRAIN_MODEL: "bkp/run3/28-09-2020-19-10-42_vgg11_run1/checkpoint/model_24_best_1.0.pth"
